# Generated by Django 4.2.7 on 2025-05-21 16:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_summary_month_summary_year_alter_summary_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='summary',
            unique_together={('user', 'year', 'month')},
        ),
    ]
