# Generated by Django 4.2.7 on 2025-05-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_summary_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='incomes',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date',
            field=models.DateField(),
        ),
    ]
