# Generated by Django 4.2.7 on 2025-06-01 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0007_alter_expenses_description_alter_incomes_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-date'], 'verbose_name': 'Wydatek', 'verbose_name_plural': 'Wydatki'},
        ),
        migrations.AlterModelOptions(
            name='expensescategory',
            options={'verbose_name': 'Kategoria Wydatku', 'verbose_name_plural': 'Kategorie Wydatków'},
        ),
        migrations.AlterModelOptions(
            name='incomes',
            options={'ordering': ['-date'], 'verbose_name': 'Przychód', 'verbose_name_plural': 'Przychody'},
        ),
        migrations.AlterModelOptions(
            name='incomescategory',
            options={'verbose_name': 'Kategoria Przychodu', 'verbose_name_plural': 'Kategorie Przychodów'},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name': 'Podsumowanie Miesięczne', 'verbose_name_plural': 'Podsumowania Miesięczne'},
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Kwota wydatku (np. 50.00).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.ForeignKey(help_text='Kategoria, do której przypisany jest ten wydatek.', on_delete=django.db.models.deletion.CASCADE, to='myapp.expensescategory'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(help_text='Data poniesienia wydatku (format YYYY-MM-DD).'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.TextField(blank=True, help_text='Opcjonalny, szczegółowy opis wydatku.', null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='user',
            field=models.ForeignKey(help_text='Użytkownik, do którego należy ten wydatek.', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensescategory',
            name='category',
            field=models.CharField(help_text="Nazwa kategorii wydatku (np. 'Jedzenie', 'Transport', 'Rozrywka').", max_length=255),
        ),
        migrations.AlterField(
            model_name='expensescategory',
            name='user',
            field=models.ForeignKey(help_text='Użytkownik, do którego należy ta kategoria wydatków.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Kwota przychodu (np. 1500.00).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='category',
            field=models.ForeignKey(help_text='Kategoria, do której przypisany jest ten przychód.', on_delete=django.db.models.deletion.CASCADE, to='myapp.incomescategory'),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date',
            field=models.DateField(help_text='Data uzyskania przychodu (format YYYY-MM-DD).'),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='description',
            field=models.TextField(blank=True, help_text='Opcjonalny, szczegółowy opis przychodu.', null=True),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='user',
            field=models.ForeignKey(help_text='Użytkownik, do którego należy ten przychód.', on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incomescategory',
            name='category',
            field=models.CharField(help_text="Nazwa kategorii przychodu (np. 'Wynagrodzenie', 'Premia').", max_length=255),
        ),
        migrations.AlterField(
            model_name='incomescategory',
            name='user',
            field=models.ForeignKey(help_text='Użytkownik, do którego należy ta kategoria przychodów.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='summary',
            name='balance',
            field=models.DecimalField(decimal_places=2, help_text='Bilans finansowy (total_income - total_expense) dla danego miesiąca.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='summary',
            name='month',
            field=models.IntegerField(help_text='Miesiąc (1-12), do którego odnosi się podsumowanie (np. 6 dla czerwca).'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, help_text='Całkowita suma wydatków w danym miesiącu.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='summary',
            name='total_income',
            field=models.DecimalField(decimal_places=2, help_text='Całkowita suma przychodów w danym miesiącu.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='summary',
            name='user',
            field=models.ForeignKey(help_text='Użytkownik, do którego należy to podsumowanie.', on_delete=django.db.models.deletion.CASCADE, related_name='summary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='summary',
            name='year',
            field=models.IntegerField(help_text='Rok, do którego odnosi się podsumowanie (np. 2024).'),
        ),
        migrations.AlterUniqueTogether(
            name='incomescategory',
            unique_together={('user', 'category')},
        ),
    ]
