# Generated by Django 4.2.7 on 2025-06-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_expenses_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
